### ISSUE TITLE
Pure Wayland crashes on start

### ISSUE THREAD

**Issue by TheHooly** [flathub/org.prismlauncher.PrismLauncher#36]
OS: Fedora Kinoite 38
Overrides: Added Wayland, removed X11 and IPC

According to https://github.com/flathub/org.prismlauncher.PrismLauncher/pull/17 the game should run under native Wayland when available.

With both Wayland and X11 available, the game runs under X11.
With only Wayland available, the game crashes on start with the following error message:
```
GLFW error 65548: Wayland: The platform does not support setting the window icon.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
press enter to continue [10:23:49] [Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65548: Wayland: The platform does not support setting the window icon
	at net.minecraft.class_1041.method_4501(class_1041.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokePPV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:2336) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:2368) ~[lwjgl-glfw-3.3.1.jar:?]
	at net.minecraft.class_1041.method_4491(class_1041.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Der Prozess wurde mit Status 0 beendet.
```
Full log: https://pastebin.com/Xc2WAZeY

**Comment by TheHooly** [comment]
Forgot to add `-Dorg.lwjgl.glfw.libname=/app/lib/libglfw.so` to the Java arguments.
