### ISSUE TITLE
Flatpak version of the launcher prevents the game from launching with a Wayland-first GLFW native.

### ISSUE THREAD

**Issue by LemonHeadOnGit** [flathub/org.prismlauncher.PrismLauncher#67]
This process used to work, but at some point during the past month or so the game would consistently fail to load with a GLFW native that prefers Wayland over X11 (pretty much GLFW 3.4+).

While this isn't necessarily an issue that makes the game unplayable in any way, it does mean that if you do have such a set up the game **is** unplayable.

The crashing point is this trace:
```
java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]Wayland: Failed to connect to display
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:77)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:509)
	at fgo.<init>(SourceFile:502)
	at net.minecraft.client.main.Main.main(SourceFile:239)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**The game does however function as normal with the custom native in the _non-flatpak version_ of the launcher.**
> The above issue is based off of accounts from this issue: https://github.com/Admicos/minecraft-wayland/issues/64, as well as experiences of my own

**Comment by zefr0x** [comment]
Is this a duplicate of #64 ?

**Comment by LemonHeadOnGit** [comment]
> Is this a duplicate of #64 ?
> 
> Are you using the Nvidia drivers?

Hi!
I have tried running with the environment variable:
`__GL_THREADED_OPTIMIZATIONS=0`
but the problem still exists.

I also forgot to mention that my error trace above specifically happens with the VulkanMod, but since then I have also noticed that it happens with Sodium, regardless of whether I have `__GL_THREADED_OPTIMIZATIONS` set.

Looking further into it, other Flatpak applications with my setup seem to have troubles working with Vulkan. And yes, I am using the Nvidia non-open drivers, but I have also tried with the open kernel variant.
